[package]
name = "nixcards-store"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
nixcards-core = { path = "../nixcards-core" }
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
